import re

club_abbreviations = {
    "A": "Authors",
    "Ad": "Alpha Delta Phi",
    "Ag": "St. Andrews Golf Club",
    "Ant": "Amherst Graduate",
    "An": "Army & Navy",
    "Ar": "Sons American Revolution ",
    "As": "Ardsley",
    "Ats": "National Arts",
    "Ay": "American S acht",
    "Bd": "Barnard",
    "Bg": "Baltusrol Golf Club",
    "Bow": "Bowdoin Graduate",
    "Br": "Brown University Graduate ",
    "Bk": "Brooklyn",
    "С": "Century",
    "Cal": "Calumet",
    "Cc": "Society of the Cincinnati",
    "Cd": "Colonial Dames",
    "Cda": "Colonial Dames of America",
    "Ch": "Church",
    "CI": "Columbia Graduate",
    "Cn": "Corinthian Yacht",
    "Col": "Colonial",
    "Cr1": "Cornell Graduate",
    "Ct": "City",
    "Cth": "Catholic",
    "Cw": "Society of Colonial Wars",
    "Cy": "Country",
    "Dar": "Daughters American Revolution",
    "Dc": "Daughters of the Cincinnati",
    "Dke": "Delta Kappa Epsilon",
    "Dm": "Democratic",
    "Dp": "Delta Phi",
    "Dt": "Down Town",
    "Dth": "Dartmouth Graduate",
    "Du": "Delta Upsilon",
    "Dv": "Deutcher Verein",
    "E": "Essex of Newark",
    "Ec": "Essex Co. Country",
    "Eg": "Engineers",
    "Fn": "Fencers",
    "Fw": "Foreign Wars (Military Order of)",
    "G": "Grolier",
    "H": "Harvard Graduate",
    "Ha": "Hamilton of Brooklyn",
    "Ham": "Hamilton Graduate",
    "HI": "Holland Society",
    "Hob": "Hobart Graduate",
    "JHop": "Johns Hopkins Graduate",
    "Jkl": "Jekyl Island Club",
    "К": "Knickerbocker",
    "Kg": "Knollwood",
    "L": "Lawyers",
    "Lc": "Larchmont Yacht",
    "LI": "Loyal Legion",
    "Lt": "Lotus",
    "M": "Manhattan",
    "Mb": "Meadow Brook",
    "Mc": "Merchants",
    "Mg": "Morris County Golf",
    "Mo": "Morristown",
    "Mt": "Metropolitan",
    "Mtw": "Metropolitan of Washington",
    "Myf": "Mayflower Descendants",
    "N": ". New York",
    "N": "University of New York Graduate",
    "Na": "N. Y. Athletic",
    "Ny": "N. Y. Yacht",
    "P": "Princeton Graduate",
    "PI": "Players",
    "Pn": "University of Pa. Graduate",
    "Pu": "Psi Upsilon",
    "R": "Racquet",
    "Rens": "Rensselaer Polytechnic Graduate",
    "Rf": "Reform",
    "Rg": "Riding",
    "Rh": "Rockway Hunt",
    "Rp": "Republican",
    "Rut": "Rutgers Graduate",
    "Rv": "Sons of Revolution",
    "S": "Seawanhaka Cor. Yacht",
    "Sa": "St. Anthony",
    "Sg": "Shinnecock Golf Club",
    "SI": "Strollers",
    "Sn": "St. Nicholas",
    "Snc": "St. Nicholas Society",
    "So": "Southern Society",
    "Ss": "South Side",
    "T": "Tuxedo",
    "Tf": "Turf & Field",
    "Ту": "Trinity Graduate",
    "U": "Union College Graduate",
    "Un": "Union",
    "Ul": "Union League",
    "USA": "US Army",
    "USN": "US Navy",
    "Uv": "University",
    "W": "Whist",
    "Wk": "Westminster Kennel",
    "Wms": "Williams Graduate",
    "Wt": "Society War 1812",
    "Y": "Yale Graduate",
    "Zp": "Zeta Psi"
}

multiTokenLastName = [
    "du",
    "de",
    "van",
    "o'"
]

def validateClubName(prediction):
    return re.sub(r'[^A-z]+', '', prediction) in club_abbreviations

def isMultiTokenLastName(token):
    return token in multiTokenLastName